# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3cafcb01f454033d74f3ca8a830cf942600c9e4f59e4fef21dfdcac0afbfe4e1ffe214a0fba0a00aceeaeb41a44e0289677ab2b5a683a0a1707571132251fb4

test:
  secret_key_base: 54eb6640be3fcc1cdd5666bd3752b342270f46cb804fa443f49d2d47043bebf0d94571f87840a8b9cf5e487d4d9c15e1a541c7263b80cd49a24f22594c93d57c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
